---
title: "graph_analyse_publi"
author: "Olivier Leroy"
date: "12/2/2020"
output: 
    bookdown::html_document2:
        theme: readable
        toc: true
        toc_float: true
        number_sections: true
        toc_depth: 3
        fig_caption: true
        keep_md: true
        code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/home/defuneste/Documents/recherche/gouramic/gouramic-db-analyses/")
library(ggplot2)
library(sf)
library(stringr)
library(dplyr)
library(lubridate)
```

# Résultats des deux géocodages

## chargements des données

```{r looad}
#CLB
geocodage_clbv2.shp <- sf::st_read("data/sortie_15_04.shp" , stringsAsFactors = FALSE)
#correction formatage
geocodage_clbv2.shp$date_start <- parse_date_time(geocodage_clbv2.shp$date_start, orders = c("my", "dmy"))
geocodage_clbv2.shp$date_end_a <- parse_date_time(geocodage_clbv2.shp$date_end_a, orders = c("my", "dmy"))

# fichier de geocodage EVS
geocodage_evs.shp <- sf::st_read("data/geocodev2.geojson", stringsAsFactors = FALSE)
geocodage_evs.shp$Date_birth <- as.Date(geocodage_evs.shp$Date_birth, origin = "1899-12-30")
geocodage_evs.shp$Date_start <- as.Date(geocodage_evs.shp$Date_start, origin = "1899-12-30")
geocodage_evs.shp$Date_end <- as.Date(geocodage_evs.shp$Date_end, origin = "1899-12-30")

# library(rcartocolor)
# display_carto_all(colorblind_friendly = TRUE)
```
## Préparation des données

```{r prepa}
geocodage_clbv2.shp <- geocodage_clbv2.shp %>% 
    dplyr::select(ID_CARTO, precision = Loc_name)


geocodage_evs.shp <- geocodage_evs.shp %>% 
    dplyr::select(ID_CARTO = Id_cart, precision = result_type ) %>% 
    st_transform(2154)

```

## resultats geocodage

```{r}
geocodage_clbv2.shp  %>% 
    ggplot(aes(x = precision, fill = precision)) +
    geom_bar() +
    ylab("nbr") +
    theme_bw() # +
    # scale_color_brewer(palette="safe") # à verifier c'est pour les color blinds 
## ID_CARTO
```

```{r}
table(geocodage_clbv2.shp$precision, useNA = "ifany")/sum(table(geocodage_clbv2.shp$precision, useNA = "ifany"))*100
sum((table(geocodage_clbv2.shp$precision, useNA = "ifany")/sum(table(geocodage_clbv2.shp$precision, useNA = "ifany"))*100)[1:4])

```

```{r}
table(geocodage_evs.shp$precision, useNA = "ifany")/sum(table(geocodage_evs.shp$precision, useNA = "ifany"))*100
```

## distance 

```{r}
# on vire les NA ou on a pas de loc
geocodage_clbv2.shp <- geocodage_clbv2.shp[!is.na(geocodage_clbv2.shp$precision),] 
geocodage_evs.shp <- geocodage_evs.shp[!is.na(geocodage_evs.shp$precision),]
geocodage_evs.shp  <- geocodage_evs.shp[!st_is_empty(geocodage_evs.shp$geometry),]
## on ne va garder que ceux présent dans le codage ESRI

bob <- rbind(geocodage_clbv2.shp[geocodage_clbv2.shp$ID_CARTO %in% geocodage_evs.shp$ID_CARTO,],
             geocodage_evs.shp)

join_adresse <- bob %>% group_by(ID_CARTO) %>%  summarize(test = first(precision)) %>% st_cast("LINESTRING")

join_adresse$distance <- st_length(join_adresse)
boxplot(join_adresse$distance)

join_adresse[as.numeric(join_adresse$distance) > 5,]

st_write(join_adresse,  "data/verif/distance.shp")
```

